# Generated by Django 4.0.3 on 2022-03-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_date_alter_order_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='file',
        ),
        migrations.AddField(
            model_name='order',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachment/%Y/%m/%d/'),
        ),
    ]
