# Generated by Django 4.0.3 on 2022-03-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_file_order_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d/'),
        ),
    ]
